name: Transform Leetcode File Names
on: [push]
jobs:
  Transform-Leetcode-Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: List files in the repository
        run: |
          	ls ${{ github.workspace }}
		  	SAVEIFS=$IFS
			IFS=$(echo -en "\n\b")
			for file in `ls leetcode`; do
				if [ ! -f "$file" ]; then
					cleanName=`tr '[:blank:]' '-' <<< "$file"`
					cleanName=`tr '[:upper:]' '[:lower:]' <<< "$cleanName"`
					if [ $file != $cleanName ]; then
						mv "$file" $cleanName
					fi
				fi
			done
			IFS=$SAVEIFS
      - run: echo "🍏 This job's status is ${{ job.status }}."
