name: Transform Leetcode File Names
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  Transform-Leetcode-Files:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Run a file transform script
        uses: actions/checkout@v1
      - run: sh ./.github/workflows/transform-leetcode-files.sh
      - name: switching from HTTPS to SSH
        run: "git remote set-url origin ${{ secrets.ssh }}"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Auto updating leetcode file names"
      - name: fetch from main
        run: git fetch origin main
      - name: push code to main
        run: "git push origin HEAD:main"
      - run: echo "This job's status is ${{ job.status }}."